CC = gcc
O_FILES = alf.o dt.o trist.o lia.o basic.o sos.o internal.o cb.o malloc.o files.o cb_doprnt.o stack.o aux.o math2.o uhash.o prime.o time.o unweighted.o minor.o det.o weighted.o isort.o qsort.o lookup.o iit.o metrics.o combinatorics.o betti.o ml.o sig.o

getsig: getsig.c $(O_FILES)
	$(CC) getsig.c $(O_FILES) -lm -o getsig

